Watching for file changes with StatReloader
Unauthorized: /api/test_function/
Unauthorized: /api/test_function/
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 75, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
Internal Server Error: /api/profile/user1/update/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 93, in update_user_profile
    serializer = UserProfileUpdateSerializer(user, data=request.data)
NameError: name 'UserProfileUpdateSerializer' is not defined
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 75, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 76, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 76, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 76, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 78, in user_profile
    return Response(request['user'])
TypeError: 'Request' object is not subscriptable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
io.UnsupportedOperation: not readable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
io.UnsupportedOperation: not readable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
io.UnsupportedOperation: not readable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
io.UnsupportedOperation: not readable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'authenticated_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 75, in user_profile
    user_profile = UserProfile.objects.get(user=request.authenticated_user)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'authenticated_user'
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
TypeError: 'Request' object is not iterable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'authenticated_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 77, in user_profile
    return Response({'data': request.authenticated_user})
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'authenticated_user'
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 75, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/apuankka/api/views.py", line 75, in user_profile
    user_profile = UserProfile.objects.get(user=request.user)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ahmed/jupy/django_projects/src/django/django/db/models/query.py", line 629, in get
    raise self.model.DoesNotExist(
api.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
/home/ahmed/jupy/django_projects/apuankka/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/profile/user1/update/
Traceback (most recent call last):
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ahmed/jupy/django_projects/src/django/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ahmed/jupy/django_projects/src/django/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ahmed/jupy/django_projects/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserProfileSerializer is not JSON serializable
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ahmed/jupy/django_projects/apuankka/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Unauthorized: /api/test_function/
